fusion_games/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from users.views import home_view, logout_view, user_profile_view, user_profile_settings_view, user_wallet_view, \
    user_profile_security_settings_view
from pages.views import match_view, checkout_view, contact_view, cart_view, store_view, \
    error_404_view, matches_list_view, components_view, widgets_view, base_view, user_view
from matches.views import find_matches_view, current_matches_view, match_history_view, match_creation_view

urlpatterns = [
    path('', include('django.contrib.auth.urls')),

    path('', home_view, name='home'),
    path('logout/', logout_view, name='logout'),

    path('home/', user_profile_view, name='user_profile'),
    path('configurações_perfil/', user_profile_settings_view, name='settings'),
    path('configurações_seguranca/', user_profile_security_settings_view, name='security_settings'),
    path('carteira/', user_wallet_view, name='user_wallet'),

    path('procurar_partidas/', find_matches_view, name='find_matches'),
    path('minhas_partidas/', current_matches_view, name='current_matches'),
    path('historico_partidas/', match_history_view, name='match_history'),
    path('criar_partida/', match_creation_view, name='match_creation'),

    path('carrinho/', cart_view),
    path('loja/', store_view),
    path('base/', base_view),
    path('partida-2/', match_view),
    path('lista_partidas/', matches_list_view),
    path('perfil/', user_profile_view),
    path('erro_404/', error_404_view),
    path('checkout/', checkout_view),
    path('contato/', contact_view),
    path('componentes/', components_view),
    path('widgets/', widgets_view),
    path('user-profile/', user_view),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from localflavor.br.forms import BRPostalCodeField

# Create your models here.
from django.http import request


class BaseModel(models.Model):
    objects = models.Manager()

    class Meta:
        abstract = True


class Profile(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture_url = models.ImageField(upload_to='profile_picture/', default='static/assets/images/default_user.png', blank=True, null=True)
    phone = models.CharField(max_length=120, blank=False, null=True, default=None)
    cpf = models.CharField(max_length=120, blank=False, null=True, unique=True, default=None)
    birth_date = models.DateField(blank=False, null=True, default=None)
    wallet = models.DecimalField(default=0, max_digits=6, decimal_places=2, blank=False, null=False)
    psn_gametag = models.CharField(max_length=120, blank=False, null=True, default=None)
    xbox_gametag = models.CharField(max_length=120, blank=False, null=True, default=None)
    bank_name = models.CharField(max_length=120, blank=False, null=True, default=None)
    bank_account = models.CharField(max_length=120, blank=False, null=True, unique=True, default=None)
    bank_agency = models.CharField(max_length=120, blank=False, null=True, unique=True, default=None)
    bank_digit = models.CharField(max_length=120, blank=False, null=True, unique=True, default=None)
    user_status = models.CharField(max_length=120, default='available', blank=False, null=False)


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ImageField, DateField, TextInput

from users.models import Profile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]


class ImageInputForm(forms.ModelForm):
    profile_picture_url = ImageField(label='Imagem do Perfil',
                                     widget=forms.FileInput(attrs={'class': 'inputfile inputfile-1'}))

    class Meta:
        model = Profile
        fields = ['profile_picture_url']


class EditProfileForm(forms.ModelForm):
    birth_date = DateField(label='',
                           required=False,
                           widget=forms.DateInput(attrs={'data-type': 'datepicker',
                                                         'type': 'date',
                                                         'date': 'yyyy-mm-dd',
                                                         'data-datepicker': 'true',
                                                         }))
    cpf = forms.CharField(required=False)
    phone = forms.CharField(required=False)
    xbox_gametag = forms.CharField(required=False)
    psn_gametag = forms.CharField(required=False)

    class Meta:
        model = Profile
        fields = ['phone', 'birth_date', 'xbox_gametag', 'psn_gametag', 'cpf']


class EditProfileSecurityForm(forms.ModelForm):
    birth_date = DateField(required=False, label='',
                           widget=forms.DateInput(attrs={'data-type': 'datepicker',
                                                         'type': 'date',
                                                         'date': 'yyyy-mm-dd',
                                                         'data-datepicker': 'true',
                                                         }))
    cpf = forms.CharField(required=False)

    class Meta:
        model = Profile
        fields = ['cpf', 'birth_date']


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']


class EditUserSecurityForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name']


class BankInfoForm(forms.ModelForm):
    # bank_name = forms.CharField(required=False)
    # bank_account = forms.CharField(required=False)
    # bank_agency = forms.CharField(required=False)
    # bank_digit = forms.CharField(required=False)

    class Meta:
        model = Profile
        fields = ['bank_name', 'bank_account', 'bank_agency', 'bank_digit']

users/views.py
import datetime
import pprint

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.forms import model_to_dict
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect
from django.template import RequestContext


from .forms import SignUpForm, ImageInputForm, EditUserForm, EditProfileForm, EditUserSecurityForm, \
    EditProfileSecurityForm, BankInfoForm

# Create your views here.
from .models import Profile


def logout_view(request):
    logout(request)
    print('passou')
    return redirect('home')


def home_view(request, *args, **kwargs):
    signup_form = SignUpForm()
    login_context = RequestContext(request)
    msg = None
    if request.method == 'POST':
        if request.POST['username']:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            print(username, password)
            if user is not None:
                login(request, user)
                return redirect('user_profile')

            else:
                return render(request, 'index.html', {'signup_form': signup_form,
                                                      'msg': msg})
        signup_form = SignUpForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save()
            user.refresh_from_db()
            user.profile_picture_url = 'another_thing'
            user.save()
            raw_password = signup_form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            messages.success(request, 'Your profile was successfully updated!')
        else:
            error = signup_form.errors.as_data()
            msg = []
            for key in error:
                for index in range(len(error[key])):
                    validation_error = list(error[key][index])[0]
                    msg.append(validation_error)
            return render(request, 'index.html', {'signup_form': signup_form,
                                                  'msg': msg})
    return render(request, 'index.html', {'signup_form': signup_form,
                                          'msg': msg})


@login_required
def user_profile_view(request, *args, **kwargs):
    current_nav_name = 'Perfil'

    profile_model = request.user.profile
    image_input_form = ImageInputForm()
    edit_user_form = EditUserForm(initial=model_to_dict(profile_model))
    edit_profile_form = EditProfileForm(initial=model_to_dict(profile_model))

    if request.method == 'POST':
        edit_user_form = EditUserForm(request.POST, instance=request.user)
        edit_profile_form = EditProfileForm(request.POST, instance=request.user.profile)
        image_input_form = ImageInputForm(request.POST, request.FILES)

        if image_input_form.is_valid():
            user = User.objects.get(username=request.user)
            user.profile.profile_picture_url = image_input_form.cleaned_data['profile_picture_url']
            user.save()
        else:
            print(image_input_form.errors)

        if edit_profile_form.is_valid():
            edit_profile_form.save()
        else:
            print(edit_profile_form.errors)

        if request.user.first_name == '' or request.user.first_name is None:
            if request.user.last_name == '' or request.user.last_name is None:
                if edit_user_form.is_valid():
                    edit_user_form.save()
                else:
                    print(edit_user_form.errors)
                    return redirect('settings')
            return redirect('settings')
        return render(request, 'pages/user_profile.html', {'current_nav_name': current_nav_name,
                                                           'form': image_input_form,
                                                           'edit_user_form': edit_user_form,
                                                           'edit_profile_form': edit_profile_form})
    return render(request, 'pages/user_profile.html', {'current_nav_name': current_nav_name,
                                                       'form': image_input_form,
                                                       'edit_user_form': edit_user_form,
                                                       'edit_profile_form': edit_profile_form})


@login_required
def user_profile_settings_view(request, *args, **kwargs):
    current_nav_name = 'Configuracoes'
    current_menu_name = 'Dados Perfil'

    user_model = request.user
    profile_model = request.user.profile
    edit_user_form = EditUserForm()
    edit_profile_form = EditProfileForm()
    print('mare')
    if request.method == 'POST':
        edit_user_form = EditUserForm(request.POST, instance=request.user)
        edit_profile_form = EditProfileForm(request.POST, instance=request.user.profile)
        print('hare')
        if edit_profile_form.is_valid() and edit_profile_form.is_valid():
            edit_user_form.save()
            edit_profile_form.save()
            print('here')
            return render(request, 'pages/user_profile_settings.html', {'current_nav_name': current_nav_name,
                                                                        'current_menu_name': current_menu_name,
                                                                        'edit_user_form': edit_user_form,
                                                                        'edit_profile_form': edit_profile_form})

        else:
            print(edit_profile_form.errors)
            print(edit_user_form.errors)
    return render(request, 'pages/user_profile_settings.html', {'current_nav_name': current_nav_name,
                                                                'current_menu_name': current_menu_name,
                                                                'edit_user_form': edit_user_form,
                                                                'edit_profile_form': edit_profile_form})


@login_required(redirect_field_name='home')
def user_profile_security_settings_view(request, *args, **kwargs):
    """
    TODO: Ao inserir só o nome ou o só o sobrenome, não é possível inserir o outro que ficou em branco posteriormente
    :param request:
    :param args:
    :param kwargs:
    :return:
    """
    current_nav_name = 'Configuracoes'
    current_menu_name = 'Segurança'

    user_model = request.user
    profile_model = request.user.profile
    edit_user_security_form = EditUserSecurityForm(initial=model_to_dict(user_model))
    edit_profile_security_form = EditProfileSecurityForm(initial=model_to_dict(profile_model))
    edit_bank_info_form = BankInfoForm()
    if request.method == 'POST':

        edit_user_security_form = EditUserSecurityForm(request.POST, instance=request.user)
        if edit_user_security_form.is_valid():
            edit_user_security_form.save()
            return redirect('security_settings')
        else:
            print(edit_user_security_form.errors)

        edit_profile_security_form = EditProfileSecurityForm(request.POST, instance=request.user.profile)
        if edit_profile_security_form.is_valid():
            edit_profile_security_form.save()
            return redirect('security_settings')
        else:
            print(edit_profile_security_form.errors)

        edit_bank_info_form = BankInfoForm(request.POST, instance=request.user.profile)
        if edit_bank_info_form.is_valid():
            edit_bank_info_form.save()
            return redirect('security_settings')
        else:
            print(edit_bank_info_form.errors)

    return render(request, 'pages/user_profile_private_settings.html', {'current_nav_name': current_nav_name,
                                                                        'current_menu_name': current_menu_name,
                                                                        'edit_profile_form': edit_profile_security_form,
                                                                        'edit_user_security_form': edit_user_security_form,
                                                                        'edit_bank_info_form': edit_bank_info_form
                                                                        })


@login_required
def user_wallet_view(request, *args, **kwargs):
    current_nav_name = 'Carteira'
    return render(request, 'pages/user_wallet.html', {'current_nav_name': current_nav_name})

users/templates/pages/user_profile.html
{% extends 'layouts/user_base.html' %}

{% block content %}

    <div class="container youplay-content">

        <div class="row">
            <div class="col-md-9">

                <h3 class="mt-0 mb-20">{{request.user.first_name}}</h3>
                <table class="table table-bordered">
                    <tbody>
                     <tr>
                        <td style="width: 200px;"><p>Nome completo</p></td>
                        <td><p>{% if request.user.first_name == none %} {% else %}{{request.user.first_name}} {{request.user.last_name}}{% endif %}</p></td>
                    </tr>
                     <tr>
                        <td style="width: 200px;"><p>Nome de usuário</p></td>
                        <td><p>{% if request.user.username == none %} {% else %}{{request.user.username}}{% endif %}</p></td>
                    </tr>
                     <tr>
                        <td style="width: 200px;"><p>Email</p></td>
                        <td><p>{% if request.user.email == none %} {% else %}{{request.user.email}}{% endif %}</p></td>

                    <tr>
                        <td><p>WhatsApp</p></td>
                        <td><p>{% if request.user.profile.phone == none %} {% else %}{{request.user.profile.phone}}{% endif %}</p></td>
                    </tr>
                    <tr>
                        <td><p>Data Nascimento</p></td>
                        <td><p>{% if request.user.profile.birth_date == none %} {% else %}{{request.user.profile.birth_date}}{% endif %}</p></td>
                    </tr>
                    <tr>
                        <td style="width: 200px;"><p>Xbox GameTag</p></td>
                        <td><p>{% if request.user.profile.xbox_gametag == none %} {% else %}{{request.user.profile.xbox_gametag}}{% endif %}</p></td>
                    </tr>
                    <tr>
                        <td><p>PSN GameTag</p></td>
                        <td><p>{% if request.user.profile.psn_gametag == none %} {% else %}{{request.user.profile.psn_gametag}}{% endif %}</p></td>
                    </tr>
                    </tbody>
                </table>
            </div>

            <!-- Right Side -->
            <div class="col-md-3">
                <div class="side-block">
    <h4 class="block-title">About</h4>
    <div class="block-content">
        Ecce dabo Pinkman Isai OK? Sicut locutus est tibi, et datus est, et hic sine Semper consequat volumus ... et ille in urbe ista licet? Et infernus, ubi tu non Virginiae ornare vel ipsum. Ut enim Albuquerque et ille eum iure hic, et ego ducam te ad iustitiam.
    </div>
</div>
<div class="side-block">
    <h4 class="block-title">Location</h4>
    <div class="block-content pt-5">
        <div class="responsive-embed responsive-embed-16x9">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d423284.59051352815!2d-118.41173249999999!3d34.0204989!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c75ddc27da13%3A0xe22fdf6f254608f4!2z0JvQvtGBLdCQ0L3QtNC20LXQu9C10YEsINCa0LDQu9C40YTQvtGA0L3QuNGPLCDQodCo0JA!5e0!3m2!1sru!2sru!4v1430158354122" width="600" height="450"></iframe>
        </div>
    </div>
</div>
            </div>
            <!-- Right Side -->

        </div>

    </div>


{% endblock content %}

users/templates/pages/user_profile_settings.html
{% extends 'layouts/user_base.html' %}

{% block content %}

    <div class="container youplay-content">

        <div class="row">

            <div class="col-md-9">

                {% include 'includes/profile_edit_menu.html' %}

                <form id="form-profile-data" action="" method="post">  {% csrf_token %}
                    <h3>Dados Pessoais:</h3>
                    <div class="form-horizontal mt-30 mb-40">
                        {% if request.user.first_name == none or request.user.first_name == '' %}
                        <div class="form-group">
                            <label class="control-label col-sm-2"  for="id_first_name">Nome</label>
                            <div class="col-sm-10">
                                <div class="youplay-input">
                                    <p>{{edit_user_form.first_name}}</p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if request.user.last_name == none or request.user.last_name == '' %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_last_name">Sobrenome:</label>
                            <div class="col-sm-10">
                                <div class="youplay-input">
                                    <p>{{edit_user_form.last_name}}</p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_phone">Whatsapp:</label>
                            <div class="col-sm-10">
                                <div class="youplay-input">
                                    <p>{{edit_profile_form.phone}}</p>
                                </div>
                            </div>
                        </div>
                        {% if request.user.profile.birth_date == none or request.user.profile.birth_date == '' %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_birth_date">Data de Nascimento:</label>
                            <div class="col-sm-10">
                                <div class="youplay-input">
                                    <p>{{edit_profile_form.birth_date}}</p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    <h3>Dados de Network:</h3>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_xbox_gametag">Xbox Live ID:</label>
                            <div class="col-sm-10">
                                <div class="youplay-input">
                                    <p>{{edit_profile_form.xbox_gametag}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_psn_gametag">PSN ID:</label>
                            <div class="col-sm-10">
                                <div class="youplay-input">
                                    <p>{{edit_profile_form.psn_gametag}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">Salvar Dados</button>
                        </div>
                    </div>
                </form>

            </div>

            <!-- Right Side -->
            <div class="col-md-3">
                <div class="side-block">
    <h4 class="block-title">About</h4>
    <div class="block-content">
        Ecce dabo Pinkman Isai OK? Sicut locutus est tibi, et datus est, et hic sine Semper consequat volumus ... et ille in urbe ista licet? Et infernus, ubi tu non Virginiae ornare vel ipsum. Ut enim Albuquerque et ille eum iure hic, et ego ducam te ad iustitiam.
    </div>
</div>
<div class="side-block">
    <h4 class="block-title">Location</h4>
    <div class="block-content pt-5">
        <div class="responsive-embed responsive-embed-16x9">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d423284.59051352815!2d-118.41173249999999!3d34.0204989!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c75ddc27da13%3A0xe22fdf6f254608f4!2z0JvQvtGBLdCQ0L3QtNC20LXQu9C10YEsINCa0LDQu9C40YTQvtGA0L3QuNGPLCDQodCo0JA!5e0!3m2!1sru!2sru!4v1430158354122" width="600" height="450"></iframe>
        </div>
    </div>
</div>
            </div>
            <!-- Right Side -->

        </div>

    </div>

{% endblock %}