fusion_games/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from users.views import home_view, logout_view, user_profile_view, user_profile_settings_view, user_wallet_view, \
    user_profile_security_settings_view
from pages.views import match_view, checkout_view, contact_view, cart_view, store_view, \
    error_404_view, matches_list_view, components_view, widgets_view, base_view, user_view
from matches.views import find_matches_view, current_matches_view, match_history_view, match_creation_view

urlpatterns = [
    path('', include('django.contrib.auth.urls')),

    path('', home_view, name='home'),
    path('logout/', logout_view, name='logout'),

    path('home/', user_profile_view, name='user_profile'),
    path('configurações_perfil/', user_profile_settings_view, name='settings'),
    path('configurações_seguranca/', user_profile_security_settings_view, name='security_settings'),
    path('carteira/', user_wallet_view, name='user_wallet'),

    path('procurar_partidas/', find_matches_view, name='find_matches'),
    path('minhas_partidas/', current_matches_view, name='current_matches'),
    path('historico_partidas/', match_history_view, name='match_history'),
    path('criar_partida/', match_creation_view, name='match_creation'),

    path('carrinho/', cart_view),
    path('loja/', store_view),
    path('base/', base_view),
    path('partida-2/', match_view),
    path('lista_partidas/', matches_list_view),
    path('perfil/', user_profile_view),
    path('erro_404/', error_404_view),
    path('checkout/', checkout_view),
    path('contato/', contact_view),
    path('componentes/', components_view),
    path('widgets/', widgets_view),
    path('user-profile/', user_view),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from localflavor.br.forms import BRPostalCodeField

# Create your models here.
from django.http import request


class BaseModel(models.Model):
    objects = models.Manager()

    class Meta:
        abstract = True


class Profile(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture_url = models.ImageField(upload_to='profile_picture/', default='static/assets/images/default_user.png', blank=True, null=True)
    phone = models.CharField(max_length=120, blank=False, null=True, default=None)
    cpf = models.CharField(max_length=120, blank=False, null=True, unique=True, default=None)
    birth_date = models.DateField(blank=False, null=True, default=None)
    wallet = models.DecimalField(default=0, max_digits=6, decimal_places=2, blank=False, null=False)
    psn_gametag = models.CharField(max_length=120, blank=False, null=True, default=None)
    xbox_gametag = models.CharField(max_length=120, blank=False, null=True, default=None)
    bank_name = models.CharField(max_length=120, blank=False, null=True, default=None)
    bank_account = models.CharField(max_length=120, blank=False, null=True, unique=True, default=None)
    bank_agency = models.CharField(max_length=120, blank=False, null=True, unique=True, default=None)
    bank_digit = models.CharField(max_length=120, blank=False, null=True, unique=True, default=None)
    user_status = models.CharField(max_length=120, default='available', blank=False, null=False)


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ImageField, DateField, TextInput

from users.models import Profile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]


class ImageInputForm(forms.ModelForm):
    profile_picture_url = ImageField(label='Imagem do Perfil',
                                     widget=forms.FileInput(attrs={'class': 'inputfile inputfile-1'}))

    class Meta:
        model = Profile
        fields = ['profile_picture_url']


class EditProfileForm(forms.ModelForm):
    birth_date = DateField(label='',
                           required=False,
                           widget=forms.DateInput(attrs={'data-type': 'datepicker',
                                                         'type': 'date',
                                                         'date': 'yyyy-mm-dd',
                                                         'data-datepicker': 'true',
                                                         }))
    cpf = forms.CharField(required=False)
    phone = forms.CharField(required=False)
    xbox_gametag = forms.CharField(required=False)
    psn_gametag = forms.CharField(required=False)

    class Meta:
        model = Profile
        fields = ['phone', 'birth_date', 'xbox_gametag', 'psn_gametag', 'cpf']


class EditProfileSecurityForm(forms.ModelForm):
    birth_date = DateField(required=False, label='',
                           widget=forms.DateInput(attrs={'data-type': 'datepicker',
                                                         'type': 'date',
                                                         'date': 'yyyy-mm-dd',
                                                         'data-datepicker': 'true',
                                                         }))
    cpf = forms.CharField(required=False)

    class Meta:
        model = Profile
        fields = ['cpf', 'birth_date']


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']


class EditUserSecurityForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name']


class BankInfoForm(forms.ModelForm):
    # bank_name = forms.CharField(required=False)
    # bank_account = forms.CharField(required=False)
    # bank_agency = forms.CharField(required=False)
    # bank_digit = forms.CharField(required=False)

    class Meta:
        model = Profile
        fields = ['bank_name', 'bank_account', 'bank_agency', 'bank_digit']

users/views.py
import datetime
import pprint

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.forms import model_to_dict
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect
from django.template import RequestContext


from .forms import SignUpForm, ImageInputForm, EditUserForm, EditProfileForm, EditUserSecurityForm, \
    EditProfileSecurityForm, BankInfoForm

# Create your views here.
from .models import Profile


def logout_view(request):
    logout(request)
    print('passou')
    return redirect('home')


def home_view(request, *args, **kwargs):
    signup_form = SignUpForm()
    login_context = RequestContext(request)
    msg = None
    if request.method == 'POST':
        if request.POST['username']:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            print(username, password)
            if user is not None:
                login(request, user)
                return redirect('user_profile')

            else:
                return render(request, 'index.html', {'signup_form': signup_form,
                                                      'msg': msg})
        signup_form = SignUpForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save()
            user.refresh_from_db()
            user.profile_picture_url = 'another_thing'
            user.save()
            raw_password = signup_form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            messages.success(request, 'Your profile was successfully updated!')
        else:
            error = signup_form.errors.as_data()
            msg = []
            for key in error:
                for index in range(len(error[key])):
                    validation_error = list(error[key][index])[0]
                    msg.append(validation_error)
            return render(request, 'index.html', {'signup_form': signup_form,
                                                  'msg': msg})
    return render(request, 'index.html', {'signup_form': signup_form,
                                          'msg': msg})


@login_required
def user_profile_view(request, *args, **kwargs):
    current_nav_name = 'Perfil'

    profile_model = request.user.profile
    image_input_form = ImageInputForm()
    edit_user_form = EditUserForm(initial=model_to_dict(profile_model))
    edit_profile_form = EditProfileForm(initial=model_to_dict(profile_model))

    if request.method == 'POST':
        edit_user_form = EditUserForm(request.POST, instance=request.user)
        edit_profile_form = EditProfileForm(request.POST, instance=request.user.profile)
        image_input_form = ImageInputForm(request.POST, request.FILES)

        if image_input_form.is_valid():
            user = User.objects.get(username=request.user)
            user.profile.profile_picture_url = image_input_form.cleaned_data['profile_picture_url']
            user.save()
        else:
            print(image_input_form.errors)

        if edit_profile_form.is_valid():
            edit_profile_form.save()
        else:
            print(edit_profile_form.errors)

        if request.user.first_name == '' or request.user.first_name is None:
            if request.user.last_name == '' or request.user.last_name is None:
                if edit_user_form.is_valid():
                    edit_user_form.save()
                else:
                    print(edit_user_form.errors)
                    return redirect('settings')
            return redirect('settings')
        return render(request, 'pages/user_profile.html', {'current_nav_name': current_nav_name,
                                                           'form': image_input_form,
                                                           'edit_user_form': edit_user_form,
                                                           'edit_profile_form': edit_profile_form})
    return render(request, 'pages/user_profile.html', {'current_nav_name': current_nav_name,
                                                       'form': image_input_form,
                                                       'edit_user_form': edit_user_form,
                                                       'edit_profile_form': edit_profile_form})


@login_required
def user_profile_settings_view(request, *args, **kwargs):
    current_nav_name = 'Configuracoes'
    current_menu_name = 'Dados Perfil'

    user_model = request.user
    profile_model = request.user.profile
    edit_user_form = EditUserForm()
    edit_profile_form = EditProfileForm()
    print('mare')
    if request.method == 'POST':
        edit_user_form = EditUserForm(request.POST, instance=request.user)
        edit_profile_form = EditProfileForm(request.POST, instance=request.user.profile)
        print('hare')
        if edit_profile_form.is_valid() and edit_profile_form.is_valid():
            edit_user_form.save()
            edit_profile_form.save()
            print('here')
            return render(request, 'pages/user_profile_settings.html', {'current_nav_name': current_nav_name,
                                                                        'current_menu_name': current_menu_name,
                                                                        'edit_user_form': edit_user_form,
                                                                        'edit_profile_form': edit_profile_form})

        else:
            print(edit_profile_form.errors)
            print(edit_user_form.errors)
    return render(request, 'pages/user_profile_settings.html', {'current_nav_name': current_nav_name,
                                                                'current_menu_name': current_menu_name,
                                                                'edit_user_form': edit_user_form,
                                                                'edit_profile_form': edit_profile_form})


@login_required(redirect_field_name='home')
def user_profile_security_settings_view(request, *args, **kwargs):
    """
    TODO: Ao inserir só o nome ou o só o sobrenome, não é possível inserir o outro que ficou em branco posteriormente
    :param request:
    :param args:
    :param kwargs:
    :return:
    """
    current_nav_name = 'Configuracoes'
    current_menu_name = 'Segurança'

    user_model = request.user
    profile_model = request.user.profile
    edit_user_security_form = EditUserSecurityForm(initial=model_to_dict(user_model))
    edit_profile_security_form = EditProfileSecurityForm(initial=model_to_dict(profile_model))
    edit_bank_info_form = BankInfoForm()
    if request.method == 'POST':

        edit_user_security_form = EditUserSecurityForm(request.POST, instance=request.user)
        if edit_user_security_form.is_valid():
            edit_user_security_form.save()
            return redirect('security_settings')
        else:
            print(edit_user_security_form.errors)

        edit_profile_security_form = EditProfileSecurityForm(request.POST, instance=request.user.profile)
        if edit_profile_security_form.is_valid():
            edit_profile_security_form.save()
            return redirect('security_settings')
        else:
            print(edit_profile_security_form.errors)

        edit_bank_info_form = BankInfoForm(request.POST, instance=request.user.profile)
        if edit_bank_info_form.is_valid():
            edit_bank_info_form.save()
            return redirect('security_settings')
        else:
            print(edit_bank_info_form.errors)

    return render(request, 'pages/user_profile_private_settings.html', {'current_nav_name': current_nav_name,
                                                                        'current_menu_name': current_menu_name,
                                                                        'edit_profile_form': edit_profile_security_form,
                                                                        'edit_user_security_form': edit_user_security_form,
                                                                        'edit_bank_info_form': edit_bank_info_form
                                                                        })


@login_required
def user_wallet_view(request, *args, **kwargs):
    current_nav_name = 'Carteira'
    return render(request, 'pages/user_wallet.html', {'current_nav_name': current_nav_name})

users/templates/includes/profile_edit.html
    <!-- /Profile Image Form -->
    <!-- Modal -->
<!--    <link href="css/normalize.css" rel="stylesheet" type="text/css"/>-->
<!--<link href="css/datepicker.css" rel="stylesheet" type="text/css"/>-->
{% load widget_tweaks %}

<div class="modal fade" id="nav-profile_edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
            <div style="margin: 9% auto;" class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <h2 class="modal-title" id="myModalLabel">Alterar Dados</h2>
                </div>
                <div class="modal-body">

                    <form id="form-alterardados" action="" method="post">  {% csrf_token %}
                        <div class="row m-t-30 justify-content-center">
                            <div class="col-12 col-lg-6">
                                <div class="form-uptitle">
                                    <p class="form-tutorials-3">Nome</p>
                                    {% if request.user.first_name == '' or request.user.first_name == none %}
                                    <div class="youplay-input">

                                            <p>{{edit_user_form.first_name}}</p>
                                         </div>
                                        {% else %}
                                        <div class="alert" role="alert">
                                            {{request.user.first_name}}
                                        </div>
                                        {% endif %}

                                </div>
                                <div class="form-uptitle m-t-30">
                                    <p class="form-tutorials-3">E-mail</p>
                                    <div class="youplay-input">
                                        <input type="text" name="email" value="{{request.user.email}}" disabled>
                                    </div>
                                </div>
                                <div class="form-uptitle m-t-30">
                                    <p class="form-tutorials-3">Telefone</p>
                                    <div class="youplay-input">
                                        <p>{{edit_profile_form.phone}}</p>
                                    </div>
                                </div>
                                <div class="form-uptitle m-t-30">
                                    <p class="form-tutorials-3">Xbox ID</p>
                                    <div class="youplay-input">
                                        <p>{{edit_profile_form.xbox_gametag}}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-6">
                                <div class="form-uptitle m-t-30-md">
                                    <p class="form-tutorials-3">Sobrenome</p>
                                    {% if request.user.last_name == '' or request.user.last_name == none %}
                                    <div class="youplay-input">

                                            <p>{{edit_user_form.last_name}}</p>
                                         </div>
                                        {% else %}
                                        <div class="alert" role="alert">
                                            {{request.user.last_name}}
                                        </div>
                                        {% endif %}
                                </div>
                                <div class="form-uptitle m-t-30">
                                    <p class="form-tutorials-3">Data de Nascimento</p>
                                    <div class="youplay-input">
                                        {% if request.user.profile.birth_date == '' or request.user.profile.birth_date == none %}
                                             <p>  {{ edit_profile_form.birth_date}}</p>
                                        {% else %}
                                             <input type="text" name="birth_date" value="{{request.user.profile.birth_date}}" disabled>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-uptitle m-t-30">
                                    <p class="form-tutorials-3">CPF</p>
                                    <div class="youplay-input">
                                        {% if request.user.profile.cpf == '' or request.user.profile.cpf == none %}
                                            <p>{{edit_profile_form.cpf}}</p>
                                        {% else %}
                                             <input type="text" name="cpf" value="{{request.user.profile.cpf}}" disabled>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-uptitle m-t-30">
                                    <p class="form-tutorials-3">PSN ID</p>
                                    <div class="youplay-input">
                                        <p>{{edit_profile_form.psn_gametag}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row align-right m-t-30">
                                <button type="submit" class="btn btn-sm btn-success" name="button">Salvar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- /Modals -->


<script>
    $('#datepicker').datepicker();
</script>


<script>
  $(function() {
    $( "#datepicker2" ).datepicker({
         dateFormat: "yy-mm-dd",
         changeMonth: true,
         changeYear: true,
         yearRange:'1920:2020',
         defaultDate:"{{request.user.profile.birth_date}}"
    });
  });
</script>

users/templates/includes/profile_edit_menu.html
<ul class="pagination pagination-sm mt-0">
                    <li class="{% if current_menu_name == 'Dados Perfil' %}active{% else %}{% endif %}">
                        <a href="{% url 'settings' %}">Dados Perfil</a>
                    </li>
                    <li class="{% if current_menu_name == 'Segurança' %}active{% else %}{% endif %}">
                        <a href="{% url 'security_settings' %}">Segurança</a>
                    </li>
                    <li class="{% if current_menu_name == 'Dados Privados' %}active{% else %}{% endif %}">
                        <a href="{% url 'settings' %}">Dados Privados</a>
                    </li>
                </ul>

users/templates/includes/profile_image_edit.html
<style>
.inputfile {
    width: 0.1px;
    height: 0.1px;
    opacity: 0;
    overflow: hidden;
    position: absolute;
    z-index: -1;
}

.inputfile + label {
    max-width: 80%;
    font-size: 1.25rem;
    /* 20px */
    font-weight: 700;
    text-overflow: ellipsis;
    white-space: nowrap;
    cursor: pointer;
    display: inline-block;
    overflow: hidden;
    padding: 0.625rem 1.25rem;
    /* 10px 20px */
}

.no-js .inputfile + label {
    display: none;
}

.inputfile :focus + label
.inputfile .has-focus + label {
    outline: 1px dotted #000;
    outline: -webkit-focus-ring-color auto 5px;
}

.inputfile + label * {
    /* pointer-events: none; */
    /* in case of FastClick lib use */
}

.inputfile + label svg {
    width: 1em;
    height: 1em;
    vertical-align: middle;
    fill: currentColor;
    margin-top: -0.25em;
    /* 4px */
    margin-right: 0.25em;
    /* 4px */
}


/* style 1 */

.inputfile-1 + label {
    color: #f1e5e6;
    background-color: #d3394c;
}

.inputfile-1:focus + label
.inputfile-1.has-focus + label
.inputfile-1 + label :hover {
    background-color: #722040;
}
</style>
    <!-- /Profile Image Form -->
    <!-- Modal -->
    <div class="modal fade" id="nav-profile_image_edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Escolher Imagem</h4>
                </div>
                <div class="modal-body">
                    <div class="col-4 d-flex justify-content-center text-center">
                        <form method="post" name="profile_picture_url" enctype="multipart/form-data">{% csrf_token %}
                            <p>
                                  {{form.profile_picture_url}}
                            <label for="id_profile_picture_url"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 25 25"></svg> <span>Escolha uma Imagem &hellip;</span></label>
                           </p>

                            <button type="submit" class="btn btn-primary">Salvar</button>

                        </form>
                      </div>

                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
    <!-- /Modals -->